version: '3.8'

services:
  postgres:
    image: postgres:10.16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql 